FROM node:bullseye-slim

# python is needed to compile some npm packages
# RUN apt-get update || : && apt-get install python -y
RUN apt-get update && apt-get install python3 make gcc g++ -y
RUN npm install -g npm

RUN mkdir -p /home/app
WORKDIR /home/app

COPY workers.js .
COPY bullmq/ ./bullmq
COPY lib/ ./lib
COPY package.json .

RUN npm install
# RUN echo `python3 --version`

# COPY config/config.js /config/config.js
VOLUME /home/app/config

EXPOSE 3000

CMD [ "node", "workers.js" ]
