FROM node:16-slim

RUN apt-get update
RUN apt-get install python3 make gcc g++ -y
RUN npm install -g npm

COPY . /home/ibp

WORKDIR /home/ibp

RUN rm -rf config/config.local.js
RUN rm -rf node_modules
RUN rm -rf vue-spa
RUN cp config/config.js config/config.local.js
RUN npm install

# WORKDIR /home/ibp/vue-spa
# RUN rm -rf node_modules
# RUN npm install
# RUN npm run build
# WORKDIR /home/ibp