# FROM node:18
FROM node:bullseye-slim

RUN npm install -g npm
# RUN npm install -g @vue/cli

RUN mkdir -p /home/ibp
WORKDIR /home/ibp

COPY config/config.js ./config/config.js
COPY server.js .
COPY package.json .
COPY lib/ ./lib
COPY models/ ./models

RUN npm install

VOLUME [ "/home/ibp/config", "/home/ibp/keys" ]

EXPOSE 30000

CMD [ "node", "server.js" ]
