FROM mariadb

LABEL MAINTAINER="derek@metaspan.com"

# Change the working directory
WORKDIR /data

ENV dialect=mysql
ENV MARIADB_ROOT_PASSWD=thisIsASecret
ENV MARIADB_USER=ibp_monitor
ENV MARIADB_PASSWORD=ibp_monitor
ENV MARIADB_DATABASE=ibp_monitor

# Copy the database schema to the /data directory
# COPY data/schema.${dialect}.sql schema.sql
ADD data/schema.${dialect}.sql /docker-entrypoint.d/.

CMD mysql -u $MYSQL_USER -p $MYSQL_PASSWORD $MYSQL_DATABASE < schema.sql

EXPOSE 3306
