FROM node:16-slim

RUN apt-get update
RUN apt-get install python3 make gcc g++ -y curl iputils-ping netcat
RUN npm install -g npm

COPY . /home/ibp

WORKDIR /home/ibp

#RUN rm -rf config/config.local.js
RUN rm -rf node_modules
RUN rm -rf frontend
#RUN cp config/config.js config/config.local.js
RUN npm install
