export const SECOND_AS_MILLISECONDS = 1_000
export const MINUTE_AS_MILLISECONDS = 60 * SECOND_AS_MILLISECONDS
export const HOUR_AS_MILLISECONDS = 60 * MINUTE_AS_MILLISECONDS
export const DAY_AS_MILLISECONDS = 24 * HOUR_AS_MILLISECONDS
